# gitlab-ci

image:
  name: hashicorp/terraform:light
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

#cache:
#  paths:
#    - .terraform

stages:
  - plan
  - apply
  - destroy

before_script:
  - terraform --version
  - terraform init

plan:
  stage: plan
  script:
    - terraform validate
    - terraform plan

apply:
  stage: apply
  only:
    - master
  script:
    - terraform apply -auto-approve

destroy:
  stage: destroy
  when: manual
  only:
    - master
  script:
    - terraform destroy -auto-approve

after_script:
  - ls -alh
